import { Platform, StyleSheet } from 'react-native';

export const webInputReset =
  Platform.OS === 'web'
    ? ({
        outlineStyle: 'solid',
        outlineWidth: 0,
        outlineColor: 'transparent',
        borderWidth: 0,
        boxShadow: 'none',
      } as const)
    : {};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  appShell: {
    flex: 1,
  },
  topBar: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 18,
    minHeight: 64,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  topBarTitle: {
    fontFamily: 'MaruBuri',
    fontSize: 20,
    fontWeight: '400',
    color: '#36231B',
    letterSpacing: 2.4,
  },
  topBarBackWrap: {
    position: 'absolute',
    left: 16,
    top: 14,
    bottom: 18,
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  topBarBack: {
    fontSize: 40,
    lineHeight: 42,
    fontWeight: '400',
    color: '#36231B',
  },
  mainArea: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 150,
    gap: 16,
  },
  homeContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 150,
  },
  featuredRail: {
    paddingRight: 28,
    gap: 14,
  },
  homeRailTitle: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 18,
    fontWeight: '600',
    color: '#1F1B18',
    marginTop: 10,
    marginBottom: 12,
  },
  homeRailTitleSpaced: {
    marginTop: 28,
  },
  homeIntro: {
    marginBottom: 18,
    gap: 2,
  },
  homeSearchWrap: {
    marginBottom: 18,
    height: 58,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 18,
    gap: 11,
    shadowColor: '#000000',
    shadowOpacity: 0.06,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  homeSearchInput: {
    fontFamily: 'MaruBuri',
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    color: '#36231B',
    padding: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
    ...webInputReset,
  },
  homeSearchPlaceholder: {
    fontFamily: 'MaruBuri',
    flex: 1,
    fontSize: 15,
    color: '#AFACA6',
  },
  homeSearchValue: {
    fontFamily: 'MaruBuri',
    flex: 1,
    fontSize: 15,
    color: '#36231B',
  },
  searchScreen: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  recipesScreen: {
    flex: 1,
    paddingTop: 4,
  },
  recipesHeader: {
    paddingHorizontal: 20,
    marginBottom: 14,
  },
  recipesTitle: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 22,
    fontWeight: '600',
    color: '#1F1B18',
  },
  recipesCount: {
    fontFamily: 'MaruBuri',
    fontSize: 13,
    color: '#8C6D5E',
    marginTop: 4,
  },
  recipeFilterScroll: {
    flexGrow: 0,
    flexShrink: 0,
  },
  recipeFilterRow: {
    paddingHorizontal: 20,
    paddingRight: 28,
    gap: 8,
    paddingBottom: 16,
  },
  recipesListScroll: {
    flex: 1,
  },
  calendarContent: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 150,
  },
  calMonthBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  calMonthNav: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calMonthNavText: {
    fontSize: 26,
    color: '#36231B',
  },
  calMonthLabel: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 18,
    fontWeight: '600',
    color: '#1F1B18',
  },
  calWeekRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  calGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calCell: {
    width: '14.2857%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calWeekText: {
    fontFamily: 'MaruBuri',
    fontSize: 12,
    color: '#9A948D',
  },
  calSunday: {
    color: '#D85C43',
  },
  calSaturday: {
    color: '#5478A8',
  },
  calDay: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calDaySelected: {
    backgroundColor: '#36231B',
  },
  calDayText: {
    fontFamily: 'MaruBuri',
    fontSize: 14,
    color: '#3F2F27',
  },
  calDayTextSelected: {
    color: '#FFF9F4',
    fontWeight: '700',
  },
  calDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    marginTop: 3,
    backgroundColor: 'transparent',
  },
  calDotActive: {
    backgroundColor: '#D85C43',
  },
  calDotOnSelected: {
    backgroundColor: '#F3D9AC',
  },
  calLogSection: {
    marginTop: 18,
    gap: 10,
  },
  calLogTitle: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 16,
    fontWeight: '600',
    color: '#1F1B18',
    marginBottom: 2,
  },
  calLogEmpty: {
    fontFamily: 'MaruBuri',
    fontSize: 14,
    color: '#947B6E',
    paddingVertical: 8,
  },
  calMealBlock: {
    gap: 8,
    marginTop: 6,
  },
  calMealLabel: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 14,
    fontWeight: '600',
    color: '#7B5C4E',
  },
  calMealEmpty: {
    fontFamily: 'MaruBuri',
    fontSize: 13,
    color: '#B6A99E',
    paddingVertical: 2,
  },
  calRecipeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: '#FFF9F4',
    borderRadius: 16,
    padding: 14,
  },
  calRecipeEmoji: {
    fontSize: 30,
  },
  calRecipeText: {
    flex: 1,
  },
  calRecipeTitle: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 16,
    fontWeight: '600',
    color: '#1F1B18',
  },
  calRecipeMeta: {
    fontFamily: 'MaruBuri',
    fontSize: 13,
    color: '#8C6D5E',
    marginTop: 2,
  },
  calRecipeChevron: {
    fontSize: 22,
    color: '#B6A99E',
  },
  recipeFilterChip: {
    height: 36,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: '#F3ECE2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recipeFilterChipActive: {
    backgroundColor: '#36231B',
  },
  recipeFilterText: {
    fontFamily: 'MaruBuri',
    fontSize: 13,
    fontWeight: '600',
    color: '#7B5C4E',
  },
  recipeFilterTextActive: {
    color: '#FFF9F4',
  },
  recipesList: {
    paddingHorizontal: 20,
    paddingBottom: 150,
    gap: 12,
  },
  searchClear: {
    fontSize: 14,
    color: '#AFACA6',
  },
  searchResults: {
    paddingBottom: 150,
    gap: 12,
  },
  searchCount: {
    fontFamily: 'MaruBuri',
    fontSize: 13,
    color: '#8C6D5E',
    marginBottom: 2,
  },
  searchHint: {
    fontFamily: 'MaruBuri',
    fontSize: 14,
    lineHeight: 21,
    color: '#947B6E',
    paddingTop: 24,
    textAlign: 'center',
  },
  searchIcon: {
    width: 17,
    height: 17,
  },
  searchIconGlass: {
    width: 13,
    height: 13,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: '#BDBAB4',
  },
  searchIconHandle: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 7,
    height: 2,
    borderRadius: 2,
    backgroundColor: '#BDBAB4',
    transform: [{ rotate: '45deg' }],
  },
  homeIntroEyebrow: {
    fontFamily: 'MaruBuri',
    fontSize: 12,
    color: '#9A948D',
    marginBottom: 10,
  },
  homeIntroTitle: {
    fontFamily: 'MaruBuri',
    fontSize: 18,
    lineHeight: 26,
    fontWeight: '700',
    color: '#1F1B18',
  },
  homeIntroSubtitle: {
    fontFamily: 'MaruBuri',
    fontSize: 15,
    lineHeight: 22,
    color: '#1F1B18',
  },
  featuredCard: {
    backgroundColor: '#F2F1ED',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    width: 168,
  },
  featuredEmoji: {
    fontSize: 98,
    textAlign: 'center',
    marginTop: 0,
  },
  featuredBody: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 12,
    gap: 2,
  },
  featuredTitle: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 18,
    lineHeight: 24,
    minHeight: 48,
    fontWeight: '600',
    color: '#1F1B18',
  },
  featuredMeta: {
    fontFamily: 'MaruBuri',
    color: '#8E857D',
    fontSize: 12,
    fontWeight: '400',
  },
  featuredInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 6,
  },
  featuredInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  featuredTimeIcon: {
    fontSize: 12,
    color: '#8B8B8B',
  },
  featuredStarIcon: {
    fontSize: 12,
    color: '#F6B73C',
  },
  featuredInfo: {
    fontFamily: 'MaruBuri',
    fontSize: 12,
    color: '#6B5F56',
  },
  featuredImageArea: {
    minHeight: 150,
    backgroundColor: '#F2F1ED',
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 18,
    justifyContent: 'center',
  },
  featuredImage: {
    width: '100%',
    height: 150,
    borderRadius: 18,
    resizeMode: 'cover',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  sectionTitle: {
    fontFamily: 'MaruBuri',
    fontSize: 18,
    fontWeight: '800',
    color: '#36231B',
  },
  sectionAction: {
    fontFamily: 'MaruBuri',
    color: '#A34C31',
    fontSize: 14,
    fontWeight: '700',
  },
  listCard: {
    backgroundColor: '#FFF9F4',
    borderRadius: 22,
    padding: 16,
    gap: 12,
  },
  listCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  listCardEmoji: {
    fontSize: 28,
  },
  listCardImage: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: '#F2F1ED',
  },
  listCardTextBlock: {
    flex: 1,
  },
  listCardTitle: {
    fontFamily: 'MaruBuri',
    fontSize: 18,
    fontWeight: '800',
    color: '#36231B',
  },
  listCardMeta: {
    fontFamily: 'MaruBuri',
    fontSize: 13,
    color: '#8C6D5E',
  },
  favoriteToggle: {
    fontSize: 24,
    color: '#D85C43',
  },
  cardSnippet: {
    fontFamily: 'MaruBuri',
    color: '#5F463B',
    fontSize: 14,
    lineHeight: 20,
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tagChip: {
    backgroundColor: '#F3E0CF',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tagText: {
    fontFamily: 'MaruBuri',
    color: '#7B5544',
    fontSize: 12,
    fontWeight: '700',
  },
  screenTitle: {
    fontFamily: 'MaruBuri',
    fontSize: 24,
    fontWeight: '800',
    color: '#36231B',
    marginBottom: 8,
  },
  screenDescription: {
    fontFamily: 'MaruBuri',
    fontSize: 14,
    lineHeight: 21,
    color: '#947B6E',
    marginBottom: 8,
  },
  primaryOption: {
    backgroundColor: '#36231B',
    borderRadius: 24,
    padding: 20,
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
  },
  secondaryOption: {
    backgroundColor: '#FFF9F4',
    borderRadius: 24,
    padding: 20,
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8D7CA',
  },
  optionIconFrame: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionLinkIcon: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  optionLinkLoop: {
    width: 12,
    height: 8,
    borderWidth: 1.5,
    borderRadius: 999,
    transform: [{ rotate: '-35deg' }],
  },
  optionLinkBridge: {
    width: 7,
    height: 1.5,
    marginHorizontal: -2,
  },
  optionNoteIcon: {
    width: 18,
    height: 18,
    justifyContent: 'center',
  },
  optionNoteSheet: {
    width: 14,
    height: 16,
    borderWidth: 1.5,
    borderRadius: 3,
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  optionNoteLine: {
    height: 1.5,
    borderRadius: 999,
    marginBottom: 3,
  },
  optionNoteLineShort: {
    width: 7,
    height: 1.5,
    borderRadius: 999,
  },
  optionPenBody: {
    position: 'absolute',
    width: 9,
    height: 1.5,
    right: -1,
    bottom: 2,
    transform: [{ rotate: '-35deg' }],
  },
  optionTextBlock: {
    flex: 1,
    gap: 4,
  },
  optionTitle: {
    fontFamily: 'MaruBuri',
    fontSize: 18,
    fontWeight: '800',
    color: '#36231B',
  },
  optionTitleOnDark: {
    fontFamily: 'MaruBuri',
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  optionDescription: {
    fontFamily: 'MaruBuri',
    fontSize: 14,
    lineHeight: 20,
    color: '#71594D',
  },
  optionDescriptionOnDark: {
    fontFamily: 'MaruBuri',
    fontSize: 15,
    lineHeight: 22,
    color: '#FFFFFF',
  },
  panel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 18,
    gap: 10,
  },
  label: {
    fontFamily: 'MaruBuri',
    fontSize: 15,
    fontWeight: '800',
    color: '#36231B',
  },
  helperText: {
    fontFamily: 'MaruBuri',
    fontSize: 13,
    color: '#8C6D5E',
  },
  input: {
    fontFamily: 'MaruBuri',
    backgroundColor: '#F6EFE7',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 15,
    color: '#36231B',
    borderWidth: 0,
    ...webInputReset,
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  primaryButton: {
    backgroundColor: '#D85C43',
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
  },
  primaryButtonText: {
    fontFamily: 'MaruBuri',
    color: '#FFF9F4',
    fontSize: 16,
    fontWeight: '800',
  },
  aiPreview: {
    backgroundColor: '#FCE8C8',
    borderRadius: 22,
    padding: 18,
    gap: 8,
  },
  aiPreviewTitle: {
    fontFamily: 'MaruBuri',
    fontSize: 16,
    fontWeight: '800',
    color: '#36231B',
  },
  aiPreviewText: {
    fontFamily: 'MaruBuri',
    fontSize: 14,
    color: '#654E43',
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 18,
    gap: 14,
  },
  photoUploadCard: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 22,
    backgroundColor: '#F6EFE7',
    overflow: 'hidden',
    marginBottom: 2,
    borderWidth: 1,
    borderColor: '#EFE4D8',
    position: 'relative',
  },
  photoUploadPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 28,
  },
  photoUploadPlus: {
    fontSize: 34,
    lineHeight: 38,
    color: '#A26A42',
    marginBottom: 10,
  },
  photoUploadTitle: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 18,
    fontWeight: '600',
    color: '#36231B',
    marginBottom: 8,
  },
  photoUploadDescription: {
    fontFamily: 'MaruBuri',
    fontSize: 13,
    lineHeight: 20,
    color: '#8C6D5E',
    textAlign: 'center',
  },
  photoUploadPreview: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  photoUploadFooter: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(246, 239, 231, 0.94)',
  },
  photoUploadAction: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 14,
    fontWeight: '600',
    color: '#7B5C4E',
  },
  photoUploadRemove: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 13,
    fontWeight: '600',
    color: '#A34C31',
  },
  fieldBlock: {
    gap: 8,
  },
  manualGridBox: {
    backgroundColor: '#F6EFE7',
    borderRadius: 18,
    width: '100%',
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
    gap: 6,
  },
  manualGridHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingBottom: 8,
  },
  manualGridRowActionSpacer: {
    width: 28,
  },
  manualGridDelete: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#EFE0D4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  manualGridDeleteText: {
    fontSize: 20,
    lineHeight: 22,
    color: '#9A7B6A',
    marginTop: -2,
  },
  manualGridHeaderText: {
    fontFamily: 'MaruBuri',
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    color: '#8B7266',
  },
  manualGridRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#E8DDD3',
  },
  manualGridInput: {
    fontFamily: 'MaruBuri',
    minWidth: 0,
    flexShrink: 1,
    fontSize: 16,
    color: '#36231B',
    paddingVertical: 4,
    backgroundColor: 'transparent',
    borderWidth: 0,
    ...webInputReset,
  },
  manualGridNameInput: {
    flex: 1,
  },
  manualGridAmountInput: {
    flex: 1,
    textAlign: 'left',
  },
  manualGridAddButton: {
    marginTop: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#FFF9F4',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E3D4C8',
  },
  manualGridAddText: {
    fontFamily: 'MaruBuri',
    color: '#7B5C4E',
    fontSize: 13,
    fontWeight: '700',
  },
  detailText: {
    fontFamily: 'MaruBuri',
    fontSize: 14,
    lineHeight: 22,
    color: '#533F36',
  },
  detailContent: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 150,
  },
  detailTitleTop: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '600',
    color: '#1F1B18',
    textAlign: 'center',
    marginBottom: 18,
  },
  detailPhoto: {
    width: '100%',
    height: 280,
    borderRadius: 20,
    backgroundColor: '#F2F1ED',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 20,
  },
  detailPhotoImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  detailPhotoEmoji: {
    fontSize: 150,
  },
  detailMetaList: {
    gap: 6,
    marginBottom: 4,
  },
  detailMetaLine: {
    fontFamily: 'MaruBuri',
    fontSize: 15,
    lineHeight: 24,
    color: '#4A4039',
  },
  detailMetaLabel: {
    fontFamily: 'MaruBuriSemiBold',
    fontWeight: '700',
    color: '#1F1B18',
  },
  detailSectionHeading: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 18,
    fontWeight: '600',
    color: '#1F1B18',
    marginTop: 26,
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E7DDD2',
  },
  detailSteps: {
    gap: 12,
  },
  detailStepText: {
    fontFamily: 'MaruBuri',
    fontSize: 15,
    lineHeight: 23,
    color: '#3F2F27',
  },
  detailStepNumber: {
    fontFamily: 'MaruBuriSemiBold',
    fontWeight: '700',
    color: '#A34C31',
  },
  detailFavoriteButton: {
    marginTop: 28,
    borderWidth: 1.5,
    borderColor: '#D85C43',
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: 'center',
  },
  detailFavoriteText: {
    fontFamily: 'MaruBuriSemiBold',
    color: '#D85C43',
    fontSize: 16,
    fontWeight: '700',
  },
  ingredientGrid: {
    borderTopWidth: 0,
  },
  ingredientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#EFE3D7',
  },
  ingredientName: {
    fontFamily: 'MaruBuri',
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#36231B',
  },
  ingredientAmount: {
    fontFamily: 'MaruBuri',
    minWidth: 92,
    marginLeft: 16,
    textAlign: 'right',
    color: '#6B4E41',
    fontSize: 15,
    fontWeight: '600',
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#F3ECE2',
    borderRadius: 0,
    borderTopWidth: 1,
    borderTopColor: '#DCCFC2',
    paddingHorizontal: 8,
    paddingTop: 10,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  navItem: {
    flex: 1,
    borderRadius: 0,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  navCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navAddButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#D85C43',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#D85C43',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  navAddIcon: {
    color: '#FFFFFF',
    fontSize: 30,
    lineHeight: 32,
    fontWeight: '300',
  },
  navIcon: {
    fontSize: 18,
    lineHeight: 20,
    color: '#9A948D',
  },
  navIconActive: {
    color: '#111111',
    fontWeight: '700',
  },
  navLabel: {
    color: '#7E786F',
    fontWeight: '600',
    fontSize: 9,
    letterSpacing: 0.4,
  },
  navLabelActive: {
    color: '#111111',
    fontWeight: '700',
  },
  mypageContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 150,
    gap: 16,
  },
  mypageProfile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    backgroundColor: '#FFF9F4',
    borderRadius: 22,
    padding: 18,
  },
  mypageAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#F3E0CF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mypageAvatarText: {
    fontSize: 28,
  },
  mypageName: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 18,
    fontWeight: '600',
    color: '#1F1B18',
  },
  mypageEmail: {
    fontFamily: 'MaruBuri',
    fontSize: 13,
    color: '#8C6D5E',
    marginTop: 2,
  },
  mypageStatsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  mypageStat: {
    flex: 1,
    backgroundColor: '#FFF9F4',
    borderRadius: 18,
    paddingVertical: 18,
    alignItems: 'center',
  },
  mypageStatvalue: {
    fontFamily: 'MaruBuriSemiBold',
    fontSize: 22,
    fontWeight: '700',
    color: '#D85C43',
  },
  mypageStatLabel: {
    fontFamily: 'MaruBuri',
    fontSize: 12,
    color: '#8C6D5E',
    marginTop: 4,
  },
  mypageMenu: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#EFE3D7',
    overflow: 'hidden',
  },
  mypageMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1E8DE',
  },
  mypageMenuText: {
    fontFamily: 'MaruBuri',
    fontSize: 15,
    color: '#3F2F27',
  },
  mypageMenuChevron: {
    fontSize: 20,
    color: '#B6A99E',
  },
});
